// this file is automatically generated by git.version.js script
export const versions = {
  revision: 'f0d2cb8',
  branch: 'master',
  remote_url: 'https://github.com/josephdadams/TallyArbiter.git'
};